/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "banco.h"

bool_t
xdr_conta (XDR *xdrs, conta *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->numero))
		 return FALSE;
	 if (!xdr_float (xdrs, &objp->saldo))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->aberta))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_param (XDR *xdrs, param *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->conta))
		 return FALSE;
	 if (!xdr_float (xdrs, &objp->valor))
		 return FALSE;
	return TRUE;
}
