/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _BANCO_H_RPCGEN
#define _BANCO_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct conta {
	int numero;
	float saldo;
	int aberta;
};
typedef struct conta conta;

struct param {
	int conta;
	float valor;
};
typedef struct param param;

#define BANCO 1000
#define VERSAO 100

#if defined(__STDC__) || defined(__cplusplus)
#define ABRECONTA 1
extern  int * abreconta_100(param *, CLIENT *);
extern  int * abreconta_100_svc(param *, struct svc_req *);
#define FECHACONTA 2
extern  int * fechaconta_100(param *, CLIENT *);
extern  int * fechaconta_100_svc(param *, struct svc_req *);
#define AUTENTICACONTA 3
extern  int * autenticaconta_100(param *, CLIENT *);
extern  int * autenticaconta_100_svc(param *, struct svc_req *);
#define DEPOSITA 4
extern  int * deposita_100(param *, CLIENT *);
extern  int * deposita_100_svc(param *, struct svc_req *);
#define RETIRA 5
extern  int * retira_100(param *, CLIENT *);
extern  int * retira_100_svc(param *, struct svc_req *);
#define SALDO 6
extern  float * saldo_100(param *, CLIENT *);
extern  float * saldo_100_svc(param *, struct svc_req *);
extern int banco_100_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define ABRECONTA 1
extern  int * abreconta_100();
extern  int * abreconta_100_svc();
#define FECHACONTA 2
extern  int * fechaconta_100();
extern  int * fechaconta_100_svc();
#define AUTENTICACONTA 3
extern  int * autenticaconta_100();
extern  int * autenticaconta_100_svc();
#define DEPOSITA 4
extern  int * deposita_100();
extern  int * deposita_100_svc();
#define RETIRA 5
extern  int * retira_100();
extern  int * retira_100_svc();
#define SALDO 6
extern  float * saldo_100();
extern  float * saldo_100_svc();
extern int banco_100_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_conta (XDR *, conta*);
extern  bool_t xdr_param (XDR *, param*);

#else /* K&R C */
extern bool_t xdr_conta ();
extern bool_t xdr_param ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_BANCO_H_RPCGEN */
