/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _BANCO_H_RPCGEN
#define _BANCO_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct conta {
	int num_conta;
};
typedef struct conta conta;

#define BANCO 200
#define VERSAO 100

#if defined(__STDC__) || defined(__cplusplus)
#define CONSULTA 1
extern  double * consulta_100(conta *, CLIENT *);
extern  double * consulta_100_svc(conta *, struct svc_req *);
extern int banco_100_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define CONSULTA 1
extern  double * consulta_100();
extern  double * consulta_100_svc();
extern int banco_100_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_conta (XDR *, conta*);

#else /* K&R C */
extern bool_t xdr_conta ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_BANCO_H_RPCGEN */
